### ISSUE TITLE
Microsoft.Graph.Models.ODataErrors.ODataError: Signature generation failed on client with:Cannot access a disposed object.

### ISSUE THREAD

**Issue by Balkoth** [microsoft/kiota-http-dotnet#236]
Using this through `<PackageReference Include="Microsoft.Graph.Core" Version="3.1.10" />`

```
Microsoft.Graph.Models.ODataErrors.ODataError: Signature generation failed on client with:Cannot access a disposed object.
Object name: 'Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle'., unable to proceed sending token request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Users.Item.Photo.Value.ContentRequestBuilder.PutAsync(Stream body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

**Comment by andrueastman** [comment]
Thanks for raising this @Balkoth 

This looks to be an error from the API as the SDK looks to have derialized this into a `ODataError` object. Any chance you can confirm the properties of the HTTP status code as well as the message? You can use the guide at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

**Comment by Balkoth** [comment]
Once i get the exception again i will post the values.
